src/scripts/services/api-service.js
Merge after https://github.com/mumuki/mumuki-classroom-api/pull/5
=> Passing course

src/scripts/config/states.js, src/scripts/controllers/guide-progress-controller.js, src/scripts/models/guide-progress-model.js, src/scripts/services/api-service.js, src/views/navbar.jade
Merge after https://github.com/mumuki/mumuki-classroom-api/pull/6
=> Improve guide progress data retrieve

src/scripts/app.js, src/scripts/controllers/guide-progress-controller.js, src/scripts/services/remember-setting-service.js
Quite useful when you are navigating between that view and student's progress, now you save that extra click to display details again. :grin:
=> Feature remember guide progress settings

config/development.js, config/production.js, config/test.js, src/scripts/config/cookies.js, src/scripts/config/http.js, src/scripts/controllers/courses-controller.js, src/scripts/controllers/exams-controller.js, src/scripts/controllers/list-header-controller.js, src/scripts/controllers/navbar-controller.js, src/scripts/controllers/new-course-controller.js, src/scripts/controllers/new-exam-controller.js, src/scripts/controllers/students-controller.js, src/scripts/controllers/teachers-controller.js, src/scripts/services/api-service.js, src/scripts/services/auth-service.js, src/scripts/services/permissions-service.js, src/views/navbar.jade
This is the last application that was missing the login update. 
Fixes mumuki/mumuki-classroom#99
Fixes mumuki/mumuki-platform#229
=> Feature sso

bower.json, src/scripts/controllers/exams-controller.js, src/scripts/controllers/exercise-progress-controller.js, src/scripts/services/api-service.js, src/scripts/services/organization-service.js, src/views/templates/item-guide-progress.jade, src/views/templates/item-student.jade
take a look to https://github.com/mumuki/mumuki-classroom-api/pull/94 first
=> Refactor database

config/development.js, config/production.js, config/test.js, src/scripts/services/auth-service.js
Fixes mumuki/mumuki-platform#254
=> Remove unused cookie

config/development.js, gulpfile.js, src/styles/_navbar.scss
fixes https://github.com/mumuki/mumuki-classroom/issues/120
Fixes https://github.com/mumuki/mumuki-platform/issues/291
=> added top to breadcrumb-list class

src/scripts/config/strings/lang_en.js, src/scripts/config/strings/lang_es.js, src/scripts/controllers/assignment-controller.js, src/scripts/controllers/modals/new-message-controller.js, src/scripts/services/api-service.js, src/scripts/services/humanizer-service.js, src/scripts/services/organization-service.js, src/styles/_new-message.scss, src/styles/main.scss, src/views/assignment.jade, src/views/modals/new-message.jade
Closes https://github.com/mumuki/mumuki-platform/issues/282
~~Merge after https://github.com/mumuki/mumuki-classroom-api/pull/110~~
Merge after https://github.com/mumuki/mumuki-office/pull/49
Still in progress, but this actually works. Please comment.
**No suggestion selected:**
**Third suggestion selected:**
=> Feature suggestions UI

gulpfile.js, src/scripts/config/strings/lang_es.js, src/scripts/controllers/exam-controller.js, src/scripts/services/api-service.js, src/scripts/services/modal-service.js, src/views/modals/confirm-dialog.jade
merge AFTER https://github.com/mumuki/mumuki-classroom-api/pull/115
fixes #103
=> added modal when exam is created to confirm

src/scripts/controllers/guide-progress-controller.js, src/scripts/controllers/list-header-controller.js, src/scripts/controllers/navbar-controller.js, src/scripts/controllers/students-controller.js, src/scripts/services/api-service.js, src/styles/_student-card.scss, src/views/navbar.jade, src/views/templates/list-header.jade
merge after https://github.com/mumuki/mumuki-classroom-api/pull/116
fixes #145
=> Feature #145 pagination

config/development.js, config/production.js, config/test.js, src/scripts/config/organization-mapper.js, test/config/organization-mapper.test.js, test/context.js
=> Issue#155 make tenant everything before domain

src/index.jade, src/scripts/config/states.js, src/scripts/services/organization-service.js
Related to https://github.com/mumuki/mumuki-classroom-api/pull/130
=> removing some organization useless code

src/views/exam.jade
Fixes #167.
Props to @fedescarpa.
=> call toggle on checkbox click

src/scripts/config/states.js
=> add curly brackets to prevent returning results

src/scripts/controllers/assignment-controller.js, src/scripts/directives/custom-editor-directive.js, src/views/assignment.jade
Resolves #172 
Also, I added support for read-only editor but didn't implement it because it's conflicting with the custom-toolbox https://github.com/mumuki/mumuki-gobstones-runner/issues/111
=> binding the lastSolutionContent and forcing rerender on exercise change

src/views/assignment.jade
:warning: Deploy after https://github.com/mumuki/mumuki-gobstones-runner/pull/112 :warning:
=> Read only custom editor

src/scripts/controllers/student-controller.js, src/views/student.jade
=> Put isMultiple within object to prevent input scope problems

src/scripts/filters/searchComparator.js, src/views/exam.jade, src/views/exams.jade, src/views/guides.jade, src/views/select.jade, src/views/teachers.jade
Fixes https://github.com/mumuki/mumuki-platform/issues/53
=> Adding custom comparator for filtering that ignores accents - Fixes mumuki/mumuki-platform#53

src/scripts/config/strings/lang_en.js, src/scripts/config/strings/lang_es.js, src/scripts/config/strings/lang_pt.js, src/scripts/controllers/exam-controller.js, src/views/exam.jade
As per the usual caveat, it works, but it looks pretty bad:
Related to mumuki/mumuki-laboratory#1108.
=> Add max submissions fields in exam view

src/scripts/config/states.js, src/scripts/controllers/edit-exam-controller.js, src/scripts/services/api-service.js, src/styles/_exam.scss, src/views/exam.jade, test/controllers/edit-exam-controller.test.js
=> Feature student paginator for exams

config/development.js, gulpfile.js, src/scripts/config/organization-mapper.js, src/scripts/config/states.js, src/scripts/controllers/home-controller.js, src/scripts/services/auth-service.js
Related to mumuki/mumukit-login#23.
Regarding the first commit: https://en.wikipedia.org/wiki/Same-origin_policy
That was preventing session cookie being set.
=> Feature unify login

src/scripts/controllers/guide-progress-controller.js, src/scripts/services/api-service.js, src/views/guide-progress.jade
Resolves #190.
:warning: Merge after https://github.com/mumuki/mumuki-classroom-api/pull/149
=> adding items to review in guide report

src/scripts/config/organization-mapper.js
=> add organization param only for login url

src/scripts/config/strings/lang_en.js, src/scripts/config/strings/lang_es.js, src/scripts/config/strings/lang_pt.js, src/scripts/controllers/new-course-controller.js
Related with https://github.com/mumuki/mumuki-classroom-api/pull/152
=> Managing 'course already exists' errors

src/scripts/controllers/assignment-controller.js, src/scripts/models/exercise-model.js, src/views/assignment.jade
=> render free form assignments

src/scripts/controllers/assignment-controller.js, src/scripts/directives/diff-directive.js, src/scripts/directives/multiple-files-directive.js, src/scripts/models/behaviors/withMultifileSupport.js, src/scripts/models/submission-model.js, src/scripts/services/api-service.js, src/views/assignment.jade, src/views/directives/multiple-files.jade
Fixes #217
Demo: https://youtu.be/M9XZJZ38l3g
=> Multiple files support - Fixes #217

src/scripts/controllers/guide-progress-controller.js, src/scripts/controllers/students-controller.js, src/styles/_student-card.scss
=> Show detached student option in the lesson detail page

src/scripts/controllers/edit-exam-controller.js
=> Save modified student list when saving exam 

src/views/guides.jade
fixes https://github.com/mumuki/mumuki-classroom-ui/issues/232
=> fixing accordion and extractin into mixin

src/index.jade, src/scripts/config/states.js, src/scripts/config/strings/lang_en.js, src/scripts/config/strings/lang_es.js, src/scripts/config/strings/lang_pt.js, src/scripts/controllers/course-controller.js, src/scripts/controllers/guide-progress-controller.js, src/scripts/controllers/list-header-controller.js, src/scripts/controllers/new-course-controller.js, src/scripts/controllers/students-controller.js, src/scripts/services/api-service.js, src/scripts/services/breadcrumb-service.js, src/scripts/services/preferences-service.js, src/views/navbar.jade, src/views/select.jade, src/views/templates/list-header.jade
Addresses #226, requires https://github.com/mumuki/mumuki-classroom-api/pull/167
=> Add all students view with basic export functionality

src/scripts/controllers/course-controller.js, src/scripts/controllers/students-controller.js, src/scripts/services/permissions-service.js, src/views/course.jade
=> Introducing and using admin permission

src/scripts/controllers/guides-controller.js, src/scripts/models/chapter-model.js, src/scripts/models/lesson-model.js, src/scripts/services/api-service.js, src/views/guides.jade
See: https://github.com/mumuki/mumuki-classroom-api/pull/218
=> Adapt GuidesController to new guides response

src/scripts/config/strings/lang_en.js, src/scripts/config/strings/lang_es.js, src/scripts/controllers/guides-controller.js, src/scripts/controllers/new-teacher-controller.js, src/scripts/directives/csv-upload-directive.js, src/scripts/models/chapter-model.js, src/scripts/models/guide-model.js, src/scripts/models/lesson-model.js, src/scripts/services/api-service.js, src/styles/_guide-progress.scss, src/views/directives/csv-upload.jade, src/views/guides.jade
see https://github.com/mumuki/mumuki-classroom-api/pull/220
=> Connect with changed endpoints
